-- Create table
create table XXL_JOB_GROUP
(
  id           NUMBER(11) generated by default as identity (maxvalue 99999999999 nocache),
  app_name     VARCHAR2(80) not null,
  title        VARCHAR2(20) not null,
  address_type NUMBER(4) not null,
  address_list VARCHAR2(512)
);
-- Add comments to the table 
comment on table XXL_JOB_GROUP
  is '定时任务组';
-- Add comments to the columns 
comment on column XXL_JOB_GROUP.app_name
  is '执行器AppName';
comment on column XXL_JOB_GROUP.title
  is '执行器名称';
comment on column XXL_JOB_GROUP.address_type
  is '执行器地址类型：0=自动注册、1=手动录入';
comment on column XXL_JOB_GROUP.address_list
  is '执行器地址列表，多地址逗号分隔';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_GROUP
  add constraint PK_JOB_GROUP primary key (ID)
  using index 
  ;

-- Create table
create table XXL_JOB_INFOF
(
  id                        NUMBER(11) generated by default as identity (maxvalue 9999999999999 nocache),
  job_group                 NUMBER(11) not null,
  job_cron                  VARCHAR2(128) not null,
  job_desc                  VARCHAR2(600),
  add_time                  TIMESTAMP(6),
  update_time               TIMESTAMP(6),
  author                    VARCHAR2(96),
  alarm_email               VARCHAR2(400),
  executor_route_strategy   VARCHAR2(50),
  executor_handler          VARCHAR2(400),
  executor_param            VARCHAR2(700),
  executor_block_strategy   VARCHAR2(50),
  executor_timeout          NUMBER(11) default 0 not null,
  executor_fail_retry_count NUMBER(11) default 0 not null,
  glue_type                 VARCHAR2(75) not null,
  glue_source               CLOB,
  glue_remark               VARCHAR2(200),
  glue_updatetime           TIMESTAMP(6),
  child_jobid               VARCHAR2(400),
  trigger_status            NUMBER(4) default 0 not null,
  trigger_last_time         NUMBER(13) default 0 not null,
  trigger_next_time         NUMBER(13) default 0 not null
);
-- Add comments to the table 
comment on table XXL_JOB_INFO
  is '定时任务信息表';
-- Add comments to the columns 
comment on column XXL_JOB_INFO.job_group
  is '执行器主键ID';
comment on column XXL_JOB_INFO.job_cron
  is '任务执行CRON';
comment on column XXL_JOB_INFO.job_desc
  is '任务描述';
comment on column XXL_JOB_INFO.add_time
  is '添加时间';
comment on column XXL_JOB_INFO.update_time
  is '更新时间';
comment on column XXL_JOB_INFO.author
  is '作者';
comment on column XXL_JOB_INFO.alarm_email
  is '报警邮件';
comment on column XXL_JOB_INFO.executor_route_strategy
  is '执行器路由策略';
comment on column XXL_JOB_INFO.executor_handler
  is '执行器任务handler';
comment on column XXL_JOB_INFO.executor_param
  is '执行器任务参数';
comment on column XXL_JOB_INFO.executor_block_strategy
  is '阻塞处理策略';
comment on column XXL_JOB_INFO.executor_timeout
  is '任务执行超时时间，单位秒';
comment on column XXL_JOB_INFO.executor_fail_retry_count
  is '失败重试次数';
comment on column XXL_JOB_INFO.glue_type
  is 'GLUE类型';
comment on column XXL_JOB_INFO.glue_source
  is 'GLUE源代码';
comment on column XXL_JOB_INFO.glue_remark
  is 'GLUE备注';
comment on column XXL_JOB_INFO.glue_updatetime
  is 'GLUE更新时间';
comment on column XXL_JOB_INFO.child_jobid
  is '子任务ID，多个逗号分隔';
comment on column XXL_JOB_INFO.trigger_status
  is '调度状态：0-停止，1-运行';
comment on column XXL_JOB_INFO.trigger_last_time
  is '上次调度时间';
comment on column XXL_JOB_INFO.trigger_next_time
  is '下次调度时间';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_INFO
  add constraint PK_JOB_INFO primary key (ID)
  using index 
  ;

-- Create table
create table XXL_JOB_LOCK
(
  lock_name VARCHAR2(75) not null
);
-- Add comments to the table 
comment on table XXL_JOB_LOCK
  is '定时任务锁';
-- Add comments to the columns 
comment on column XXL_JOB_LOCK.lock_name
  is '锁名称';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_LOCK
  add constraint PK_JOB_LOCK primary key (LOCK_NAME)
  using index 
  ;

-- Create table
create table XXL_JOB_LOG
(
  id                        NUMBER(20) generated by default as identity (maxvalue 9999999999999 nocache),
  job_group                 NUMBER(11) not null,
  job_id                    NUMBER(11) not null,
  executor_address          VARCHAR2(255),
  executor_handler          VARCHAR2(255),
  executor_param            VARCHAR2(512),
  executor_sharding_param   VARCHAR2(20),
  executor_fail_retry_count NUMBER(11) default 0 not null,
  trigger_time              TIMESTAMP(6),
  trigger_code              NUMBER(11) not null,
  trigger_msg               CLOB,
  handle_code               NUMBER(11) not null,
  handle_time               TIMESTAMP(6),
  alarm_status              NUMBER(4) default 0 not null,
  handle_msg                CLOB
);
-- Add comments to the table 
comment on table XXL_JOB_LOG
  is '任务日志表';
-- Add comments to the columns 
comment on column XXL_JOB_LOG.job_group
  is '执行器主键ID';
comment on column XXL_JOB_LOG.job_id
  is '任务，主键ID';
comment on column XXL_JOB_LOG.executor_address
  is '执行器地址，本次执行的地址';
comment on column XXL_JOB_LOG.executor_handler
  is '执行器任务handler';
comment on column XXL_JOB_LOG.executor_param
  is '执行器任务参数';
comment on column XXL_JOB_LOG.executor_sharding_param
  is '执行器任务分片参数，格式如 1/2';
comment on column XXL_JOB_LOG.executor_fail_retry_count
  is '失败重试次数';
comment on column XXL_JOB_LOG.trigger_time
  is '调度-时间';
comment on column XXL_JOB_LOG.trigger_code
  is '调度-结果';
comment on column XXL_JOB_LOG.trigger_msg
  is '调度-日志';
comment on column XXL_JOB_LOG.handle_code
  is '执行-状态';
comment on column XXL_JOB_LOG.handle_time
  is '执行-时间';
comment on column XXL_JOB_LOG.alarm_status
  is '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';
comment on column XXL_JOB_LOG.handle_msg
  is '执行-日志';
-- Create/Recreate indexes 
create index I_HANDLE_CODE on XXL_JOB_LOG (HANDLE_CODE)
  ;
create index I_TRIGGER_TIME on XXL_JOB_LOG (TRIGGER_TIME)
  ;
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_LOG
  add constraint PK_JOB_LOG primary key (ID)
  using index 
  ;

-- Create table
create table XXL_JOB_LOGGLUE
(
  id          NUMBER(11) generated by default as identity (maxvalue 99999999999 nocache),
  job_id      NUMBER(11) not null,
  glue_type   VARCHAR2(75),
  glue_source CLOB,
  glue_remark VARCHAR2(400) not null,
  add_time    TIMESTAMP(6),
  update_time TIMESTAMP(6)
);
-- Add comments to the table 
comment on table XXL_JOB_LOGGLUE
  is '定时任务GLUE';
-- Add comments to the columns 
comment on column XXL_JOB_LOGGLUE.job_id
  is '任务，主键ID';
comment on column XXL_JOB_LOGGLUE.glue_type
  is 'GLUE类型';
comment on column XXL_JOB_LOGGLUE.glue_source
  is 'GLUE源代码';
comment on column XXL_JOB_LOGGLUE.glue_remark
  is 'GLUE备注';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_LOGGLUE
  add constraint PK_JOB_LOGGLUE primary key (ID)
  using index ;

-- Create table
create table XXL_JOB_LOG_REPORT
(
  id            NUMBER(11) generated by default as identity (maxvalue 9999999999999 nocache),
  trigger_day   TIMESTAMP(6),
  running_count NUMBER(11) default 0 not null,
  suc_count     NUMBER(11) default 0 not null,
  fail_count    NUMBER(11) default 0 not null
);
-- Add comments to the table 
comment on table XXL_JOB_LOG_REPORT
  is '定时任务日志数量';
-- Add comments to the columns 
comment on column XXL_JOB_LOG_REPORT.trigger_day
  is '调度-时间';
comment on column XXL_JOB_LOG_REPORT.running_count
  is '运行中-日志数量';
comment on column XXL_JOB_LOG_REPORT.suc_count
  is '执行成功-日志数量';
comment on column XXL_JOB_LOG_REPORT.fail_count
  is '执行失败-日志数量';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_LOG_REPORT
  add constraint PK_JOB_LOG_REPORT primary key (ID)
  using index 
  ;
alter table XXL_JOB_LOG_REPORT
  add constraint KEY_I_TRIGGER_DAY unique (TRIGGER_DAY)
  using index 
  ;

-- Create table
create table XXL_JOB_REGISTRY
(
  id             NUMBER(11) generated by default as identity (maxvalue 99999999999 nocache),
  registry_group VARCHAR2(50) not null,
  registry_key   VARCHAR2(255) not null,
  registry_value VARCHAR2(255) not null,
  update_time    TIMESTAMP(6)
);
-- Add comments to the table 
comment on table XXL_JOB_REGISTRY
  is '定时任务注册';
-- Create/Recreate indexes 
create index IDX_I_G_K_V on XXL_JOB_REGISTRY (REGISTRY_GROUP, REGISTRY_KEY, REGISTRY_VALUE)
  ;
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_REGISTRY
  add constraint PK_JOB_REGISTRY primary key (ID)
  using index ;


-- Create table
create table XXL_JOB_USER
(
  id         NUMBER(11) generated by default as identity (maxvalue 99999999999 nocache),
  username   VARCHAR2(60) not null,
  password   VARCHAR2(60) not null,
  role       NUMBER(4) not null,
  permission VARCHAR2(255)
);
-- Add comments to the table 
comment on table XXL_JOB_USER
  is '定时任务用户';
-- Add comments to the columns 
comment on column XXL_JOB_USER.username
  is '账号';
comment on column XXL_JOB_USER.password
  is '密码';
comment on column XXL_JOB_USER.role
  is '角色：0-普通用户、1-管理员';
comment on column XXL_JOB_USER.permission
  is '权限：执行器ID列表，多个逗号分割';
-- Create/Recreate primary, unique and foreign key constraints 
alter table XXL_JOB_USER
  add constraint PK_JOB_USER primary key (ID)
  using index ;
alter table XXL_JOB_USER
  add constraint KEY_I_USERNAME unique (USERNAME)
  using index ;
